services:
  backend:
    container_name: no-more-bets-api
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    env_file:
      - .env
    environment:
      - AllowedOrigins=${ALLOWED_ORIGINS}
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=http://+:8080;http://+:8081
      - ConnectionStrings__DefaultConnection=Host=${POSTGRES_HOST};Port=${POSTGRES_PORT};Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - Logging__LogLevel__Default=Information
      - Logging__LogLevel__Microsoft=Warning
      - Logging__LogLevel__Microsoft.AspNetCore=Warning
      - SoccerData__ApiKey=${SOCCERDATA_API_KEY}
      - OpenAI__ApiKey=${OPENAI_API_KEY}
      - OpenAI__ModelId=${OPENAI_MODEL}
      - BraveSearch__ApiKey=${BRAVE_SEARCH_API_KEY}
      - ProxyOptions__ProxyUser=${PROXY_USER}
      - ProxyOptions__ProxyPassword=${PROXY_PASSWORD}
      - ProxyOptions__ProxyServer=${PROXY_SERVER}
      - Hangfire__Dashboard__Login=${HANGFIRE_DASHBOARD_LOGIN}
      - Hangfire__Dashboard__Password=${HANGFIRE_DASHBOARD_PASSWORD}
      - OpenTelemetry__ServiceName=${OTEL_SERVICE_NAME:-NoMoreBets}
      - OpenTelemetry__Otlp__Endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:-}
      - OpenTelemetry__Otlp__Protocol=${OTEL_EXPORTER_OTLP_PROTOCOL:-grpc}
      - OTEL_EXPORTER_OTLP_HEADERS=${OTEL_EXPORTER_OTLP_HEADERS:-}
    networks:
      - backend_db
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: no-more-bets-db
    image: postgres:17
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend_db

  frontend:
    container_name: no-more-bets-front
    build:
      context: ./no-more-bets
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:

networks:
  backend_db: