INSERT INTO "BettingEventOption" ("Id", "Name") VALUES
    (1, 'DoubleChance_HomeOrAway'),
    (2, 'DoubleChance_HomeOrDraw'),
    (3, 'DoubleChance_AwayOrDraw'),
    (4, 'MatchResult_Home'),
    (5, 'MatchResult_Away'),
    (6, 'MatchResult_Draw'),
    (7, 'BothTeamsToScore_Yes'),
    (8, 'BothTeamsToScore_No'),
    (9, 'TotalGoals_Over_0_5'),
    (10, 'TotalGoals_Under_0_5'),
    (11, 'TotalGoals_Over_1_5'),
    (12, 'TotalGoals_Under_1_5'),
    (13, 'TotalGoals_Over_2_5'),
    (14, 'TotalGoals_Under_2_5'),
    (15, 'TotalGoals_Over_3_5'),
    (16, 'TotalGoals_Under_3_5'),
    (17, 'TotalGoals_Over_4_5'),
    (18, 'TotalGoals_Under_4_5'),
    (19, 'TotalGoals_Over_5_5'),
    (20, 'TotalGoals_Under_5_5'),
    (31, 'Handicap_Home_Minus_4'),
    (32, 'Handicap_Draw_Minus_4'),
    (33, 'Handicap_Away_Plus_4'),
    (34, 'Handicap_Home_Minus_3'),
    (35, 'Handicap_Draw_Minus_3'),
    (36, 'Handicap_Away_Plus_3'),
    (37, 'Handicap_Home_Minus_2'),
    (38, 'Handicap_Draw_Minus_2'),
    (39, 'Handicap_Away_Plus_2'),
    (40, 'Handicap_Home_Minus_1'),
    (41, 'Handicap_Draw_Minus_1'),
    (42, 'Handicap_Away_Plus_1'),
    (43, 'Handicap_Home_Plus_1'),
    (44, 'Handicap_Draw_Plus_1'),
    (45, 'Handicap_Away_Minus_1'),
    (46, 'Handicap_Home_Plus_2'),
    (47, 'Handicap_Draw_Plus_2'),
    (48, 'Handicap_Away_Minus_2'),
    (49, 'Handicap_Home_Plus_3'),
    (50, 'Handicap_Draw_Plus_3'),
    (51, 'Handicap_Away_Minus_3'),
    (52, 'CorrectScore_0_0'),
    (53, 'CorrectScore_0_1'),
    (54, 'CorrectScore_0_2'),
    (55, 'CorrectScore_0_3'),
    (56, 'CorrectScore_0_4'),
    (57, 'CorrectScore_1_0'),
    (58, 'CorrectScore_1_1'),
    (59, 'CorrectScore_1_2'),
    (60, 'CorrectScore_1_3'),
    (61, 'CorrectScore_1_4'),
    (62, 'CorrectScore_2_0'),
    (63, 'CorrectScore_2_1'),
    (64, 'CorrectScore_2_2'),
    (65, 'CorrectScore_2_3'),
    (66, 'CorrectScore_2_4'),
    (67, 'CorrectScore_3_0'),
    (68, 'CorrectScore_3_1'),
    (69, 'CorrectScore_3_2'),
    (70, 'CorrectScore_3_3'),
    (71, 'CorrectScore_4_0'),
    (72, 'CorrectScore_4_1'),
    (73, 'CorrectScore_4_2'),
    (74, 'CorrectScore_4_3'),
    (75, 'CorrectScore_4_4'),
    (76, 'CorrectScore_Other')
ON CONFLICT ("Id") DO NOTHING;

INSERT INTO "MatchStatus" ("Id", "Name") VALUES
    (1, 'Upcomming'),
    (2, 'Finished')
ON CONFLICT ("Id") DO NOTHING;

INSERT INTO "MatchEventType" ("Id", "Name") VALUES
    (1, 'Goal'),
    (2, 'Assist'),
    (3, 'OwnGoal'),
    (4, 'PenaltyGoal'),
    (5, 'RedCard'),
    (6, 'YellowCard'),
    (7, 'YellowRedCard'),
    (8, 'SubstitutionIn'),
    (9, 'SubstitutionOut')
ON CONFLICT ("Id") DO NOTHING;

INSERT INTO "BettingEventType" ("Id", "Name") VALUES
    (1, 'OverUnderGoals'),
    (3, 'DoubleChance'),
    (4, 'BothTeamsToScore'),
    (5, 'MatchResult'),
    (11, 'Handicap'),
    (12, 'ExactScore')
ON CONFLICT ("Id") DO NOTHING;

INSERT INTO "BetStatus" ("Id", "Name") VALUES
    (1, 'Pending'),
    (2, 'Won'),
    (3, 'Lost'),
    (4, 'Canceled')
ON CONFLICT ("Id") DO NOTHING;

INSERT INTO "League" ("Id", "Name", "Slug", "SoccerdataId") OVERRIDING SYSTEM VALUE VALUES
  (1, 'Premier League', 'premier-league', 228),
  (2, 'Ekstraklasa', 'ekstraklasa', 279),
  (3, 'LaLiga', 'laliga', 297),
  (4, 'Bundesliga', 'bundesliga', 241),
  (5, 'Serie A', 'serie-a', 253),
  (6, 'Ligue 1', 'ligue-1', 235)
ON CONFLICT ("SoccerdataId") DO NOTHING;

-- One season per league (same competition year). Stage.SoccerdataId must match SoccerData `stage_id` for that league/season
-- (see GET /matches/?league_id=<League.SoccerdataId>&season=2025-2026 → first `stage[].stage_id`). PL below matches repo fixture (13908).
INSERT INTO "Season" ("Id", "LeagueId", "Year") OVERRIDING SYSTEM VALUE VALUES
  (1, 1, '2025-2026'),
  (2, 2, '2025-2026'),
  (3, 3, '2025-2026'),
  (4, 4, '2025-2026'),
  (5, 5, '2025-2026'),
  (6, 6, '2025-2026')
ON CONFLICT ("LeagueId", "Year") DO NOTHING;

INSERT INTO "Stage" ("Id", "SeasonId", "Name", "SoccerdataId") OVERRIDING SYSTEM VALUE VALUES
  (1, 1, 'Premier League', 13908),
  (2, 2, 'Ekstraklasa', 13950),
  (3, 3, 'LaLiga', 13947),
  (4, 4, 'Bundesliga', 13945),
  (5, 5, 'Serie A', 13906),
  (6, 6, 'Ligue 1', 13935)
ON CONFLICT ("SoccerdataId") DO NOTHING;

INSERT INTO "Club" ("Name", "Slug", "LeagueId", "SoccerdataId")
VALUES
    ('Liverpool', 'liverpool', 1, 4138),
    ('AFC Bournemouth', 'afc-bournemouth', 1, 3072),
    ('Aston Villa', 'aston-villa', 1, 2912),
    ('Newcastle United', 'newcastle-united', 1, 3071),
    ('Tottenham Hotspur', 'tottenham-hotspur', 1, 2909),
    ('Burnley', 'burnley', 1, 3104),
    ('Nottingham Forest', 'nottingham-forest', 1, 4149),
    ('Brentford', 'brentford', 1, 4148),
    ('Sunderland', 'sunderland', 1, 3073),
    ('West Ham United', 'west-ham-united', 1, 3059),
    ('Brighton & Hove Albion', 'brighton-hove-albion', 1, 3200),
    ('Fulham', 'fulham', 1, 4145),
    ('Wolverhampton Wanderers', 'wolverhampton-wanderers', 1, 3074),
    ('Manchester City', 'manchester-city', 1, 4136),
    ('Chelsea', 'chelsea', 1, 2916),
    ('Crystal Palace', 'crystal-palace', 1, 4140),
    ('Manchester United', 'manchester-united', 1, 4137),
    ('Arsenal', 'arsenal', 1, 3068),
    ('Leeds United', 'leeds-united', 1, 4147),
    ('Everton', 'everton', 1, 4139),
    ('Arka Gdynia', 'arka-gdynia', 2, 4709),
    ('Cracovia', 'cracovia', 2, 3176),
    ('GKS Katowice', 'gks-katowice', 2, 2967),
    ('Gornik Zabrze', 'gornik-zabrze', 2, 3185),
    ('Jagiellonia Bialystok', 'jagiellonia-bialystok', 2, 3500),
    ('Korona Kielce', 'korona-kielce', 2, 3186),
    ('Lech Poznan', 'lech-poznan', 2, 2956),
    ('Lechia Gdansk', 'lechia-gdansk', 2, 3180),
    ('Legia Warsaw', 'legia-warsaw', 2, 2899),
    ('Motor Lublin', 'motor-lublin', 2, 3190),
    ('Nieciecza', 'nieciecza', 2, 4713),
    ('Piast Gliwice', 'piast-gliwice', 2, 4710),
    ('Pogon Szczecin', 'pogon-szczecin', 2, 3183),
    ('Radomiak Radom', 'radomiak-radom', 2, 2964),
    ('Rakow Czestochowa', 'rakow-czestochowa', 2, 3173),
    ('Widzew Lodz', 'widzew-lodz', 2, 4715),
    ('Wisla Plock', 'wisla-plock', 2, 3179),
    ('Zaglebie Lubin', 'zaglebie-lubin', 2, 3123),
    ('Alaves', 'alaves', 3, 4892),
    ('Athletic Bilbao', 'athletic-bilbao', 3, 4887),
    ('Atletico Madrid', 'atletico-madrid', 3, 4882),
    ('Barcelona', 'barcelona', 3, 4884),
    ('Celta Vigo', 'celta-vigo', 3, 2911),
    ('Elche', 'elche', 3, 4893),
    ('Espanyol', 'espanyol', 3, 4895),
    ('Getafe', 'getafe', 3, 4891),
    ('Girona', 'girona', 3, 2798),
    ('Levante', 'levante', 3, 2914),
    ('Mallorca', 'mallorca', 3, 2802),
    ('Osasuna', 'osasuna', 3, 4888),
    ('Rayo Vallecano', 'rayo-vallecano', 3, 2910),
    ('Real Betis', 'real-betis', 3, 4886),
    ('Real Madrid', 'real-madrid', 3, 4883),
    ('Real Oviedo', 'real-oviedo', 3, 4901),
    ('Real Sociedad', 'real-sociedad', 3, 4885),
    ('Sevilla', 'sevilla', 3, 3019),
    ('Valencia', 'valencia', 3, 4890),
    ('Villarreal', 'villarreal', 3, 2907),
    ('Augsburg', 'augsburg', 4, 3116),
    ('Bayer Leverkusen', 'bayer-leverkusen', 4, 4271),
    ('Bayern Munich', 'bayern-munich', 4, 4270),
    ('Borussia Dortmund', 'borussia-dortmund', 4, 3204),
    ('Borussia M''gladbach', 'borussia-mgladbach', 4, 4272),
    ('Eintracht Frankfurt', 'eintracht-frankfurt', 4, 2998),
    ('FC Cologne', 'fc-cologne', 4, 3336),
    ('Freiburg', 'freiburg', 4, 4274),
    ('Hamburg', 'hamburg', 4, 3338),
    ('Heidenheim', 'heidenheim', 4, 4280),
    ('Hoffenheim', 'hoffenheim', 4, 3297),
    ('Mainz', 'mainz', 4, 3003),
    ('RB Leipzig', 'rb-leipzig', 4, 3292),
    ('St. Pauli', 'st-pauli', 4, 3339),
    ('Stuttgart', 'stuttgart', 4, 4276),
    ('Union Berlin', 'union-berlin', 4, 3775),
    ('Werder Bremen', 'werder-bremen', 4, 4273),
    ('Wolfsburg', 'wolfsburg', 4, 2983),
    ('AC Milan', 'ac-milan', 5, 4407),
    ('Atalanta', 'atalanta', 5, 2950),
    ('Bologna', 'bologna', 5, 2820),
    ('Cagliari', 'cagliari', 5, 4410),
    ('Como', 'como', 5, 2975),
    ('Cremonese', 'cremonese', 5, 2981),
    ('Fiorentina', 'fiorentina', 5, 2969),
    ('Genoa', 'genoa', 5, 4411),
    ('Inter Milan', 'inter-milan', 5, 3296),
    ('Juventus', 'juventus', 5, 4406),
    ('Lazio', 'lazio', 5, 3582),
    ('Lecce', 'lecce', 5, 2978),
    ('Napoli', 'napoli', 5, 2984),
    ('Parma', 'parma', 5, 4409),
    ('Pisa', 'pisa', 5, 3388),
    ('Roma', 'roma', 5, 3767),
    ('Sassuolo', 'sassuolo', 5, 4408),
    ('Torino', 'torino', 5, 3062),
    ('Udinese', 'udinese', 5, 3206),
    ('Verona', 'verona', 5, 2982),
    ('Angers', 'angers', 6, 2849),
    ('Auxerre', 'auxerre', 6, 3002),
    ('Brest', 'brest', 6, 3199),
    ('Le Havre', 'le-havre', 6, 3139),
    ('Lens', 'lens', 6, 3295),
    ('Lille', 'lille', 6, 4229),
    ('Lorient', 'lorient', 6, 4239),
    ('Lyon', 'lyon', 6, 4230),
    ('Marseille', 'marseille', 6, 3769),
    ('Metz', 'metz', 6, 4238),
    ('Monaco', 'monaco', 6, 4234),
    ('Nantes', 'nantes', 6, 4232),
    ('Nice', 'nice', 6, 3027),
    ('Paris FC', 'paris-fc', 6, 4241),
    ('PSG', 'psg', 6, 4228),
    ('Rennes', 'rennes', 6, 3001),
    ('Strasbourg', 'strasbourg', 6, 4231),
    ('Toulouse', 'toulouse', 6, 3129)
ON CONFLICT ("SoccerdataId") DO NOTHING;

INSERT INTO "Bankroll" ("Name", "Amount", "Flow", "BetId", "CreatedAt")
SELECT 'Salary', 8000, 'IN', NULL, timezone('utc', now())
WHERE NOT EXISTS (
  SELECT 1 FROM "Bankroll" WHERE "Name" = 'Salary' AND "Flow" = 'IN' LIMIT 1
);

INSERT INTO "Memory" ("Name", "Description", "Content", "CreatedAt", "UpdatedAt") VALUES
    ('STRATEGY', 'The core betting strategy and decision-making rules.', '', timezone('utc', now()), timezone('utc', now())),
    ('BANKROLL_MANAGEMENT', 'Rules and limits for managing capital.', '', timezone('utc', now()), timezone('utc', now())),
    ('GENERAL_KNOWLEDGE', 'General facts, patterns, and insights.', '', timezone('utc', now()), timezone('utc', now())),
    ('REFLECTIONS', 'Stores lessons and observations from past bets and outcomes.', '', timezone('utc', now()), timezone('utc', now())),
    ('THOUGHTS', 'Your thoughts.', '', timezone('utc', now()), timezone('utc', now())),
    ('LOG', 'Log of your operations.', '', timezone('utc', now()), timezone('utc', now()))
ON CONFLICT ("Name") DO NOTHING;
